name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Runner
        run: |
          echo "Hello Runner!"
          pwd
          whoami
          uname -a

      - name: Check Ollama
        run: |
          curl http://localhost:11434/api/tags
